### ISSUE TITLE
退出资产，重新输入时，无法获取第一个输入。

### ISSUE THREAD

**Issue by linuxu2015** [jumpserver/koko#11]
1、jumpserver版本：
1.5.0
2、koko部署方式
自己编译
3，问题现象
截图可能比较好说明
![image](https://user-images.githubusercontent.com/12248480/59995833-1f399a00-968b-11e9-8a02-22bd84d88339.png)
注意箭头指的红框，在退出上一个连接后，我输入也是oss2，但是只获取到了ss2，第一个o被忽略，在新开窗口或者clone窗口并不会出现这种现象，只有在退出一个连接时会这样。

**Comment by LeeEirc** [comment]
@linuxu2015 退出资产，第一个字符无法显示，已解决。

**Comment by ibuler** [comment]
有问题重新打开
