### ISSUE TITLE
koko占CPU资源的问题

### ISSUE THREAD

**Issue by kk545141** [jumpserver/koko#139]
看到有人反馈1.5.2版本的koko就存在占用cpu资源的问题了，而我升级到1.5.4，甚至最近lasted版本问题依旧未能消除...

该问题的表现是：正常使用过程中，一段时间后koko资源占用飙升，然后无法降下来，直到重启koko恢复。

**Comment by LeeEirc** [comment]
@kk545141 有日志吗，可以加群908100817，远程帮你看下。

**Comment by LeeEirc** [comment]
@kk545141 如果是最新的koko，开启debug模式下，可通过http://koko:5000/debug/pprof/， 查看堆栈信息，截图看一下。

**Comment by zhouyuyong** [comment]
1.5.4 遇到同样问题,在cpu异常时 使用strace追踪进程，如下
futex(0x191f188, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
read(89, "\0\0\0@\\\217\207\fs\251\373\347\230\252}\273\10\222vY\177\220\262\272\376v\200\363-\305\227\4"..., 4096) = 336
read(89, "\0\0\0\200JB\365\333\314\320\207\4\"x}W\236\272\323\\\nJ\323\224D\221\312\363\241[\272\f"..., 4096) = 232
read(89, "\0\0\0\200\265\2?$-\345\255\202;1\35o|\n\2\n\274\256\v\313\322Qt\333]k\230\336"..., 4096) = 232
read(89, "\0\0\0p\21\265\246\10{\334!g\0201\352\300P\225\213P\213!\331\203~w\31e\375\261\275H"..., 4096) = 216
read(89, "\0\0\0\200K\343m)\201\32\4x-\215\331\260\263f\32\336\23[\314\355\344\332\211<!e:\237"..., 4096) = 232
read(89, "\0\0\0\200\216R\35\0106\313\260\213\f\263\363C]\277\30\rP\276bS\321x\236\373\5@\271\23"..., 4096) = 164
read(89, "\0\0\0\220\365\307\262OOpE\222\244\247\366p\310XoC\342\23\254W\247\2j\203g0=X"..., 4096) = 180
read(89, 0xc000d1c000, 4096)            = -1 EAGAIN (Resource temporarily unavailable)
write(89, "\0\0\0\20bqm\317\r\243\253\30\340\25\nX\365\26C\303\206\25253\273\223&\350\34>\17\16"..., 52) = 52
epoll_pwait(6, {{EPOLLIN|EPOLLOUT, {u32=187457088, u64=140157855227456}}}, 128, 0, NULL) = 1
read(89, "\0\0\0010\232V\247\346\24\366\364f\237\210\251\256i\203W\374\360\372\211\300\305\201Vh\275\317\n-"..., 4096) = 408
read(89, "\0\0\1\0X\321\345\2ByIy\"]\271\3\352\343\37\367\f\246pQ#\256O\310\263\262\343;"..., 4096) = 292
read(89, "\0\0\0\200\252\211\325:\304\251\277M\206\22\27\344cb\240h\371\227[Z\v<\235\3\312\35Bu"..., 4096) = 164
read(89, 0xc000d1c000, 4096)            = -1 EAGAIN (Resource temporarily unavailable)
epoll_pwait(6, {{EPOLLIN|EPOLLOUT, {u32=187457088, u64=140157855227456}}}, 128, 0, NULL) = 1
read(89, "\0\0\0\320\343\203o}D\350\n\34\306\226\331\3\371\377\223\342\352\255X\243*\267+\302\34\1sB"..., 4096) = 244
read(89, "\0\0\0\200lg\\\17\222\255\f\332\36\332l\300\330\216\r{\2\214a\5\262\354\327\264\v\16\214+"..., 4096) = 328
read(89, "\0\0\0\220;\242'z\30\203\335}\350\235S\tZv\347\34\242\21\25I2\251\\\17!#b\215"..., 4096) = 180
read(89, "\0\0\0 \5\217\241\361X\351F\36\264\236\223(|kg'\5\250\364\335\353\237{\267\366\272i\354"..., 4096) = 68
read(89, "\0\0\0\200\254\330Y\340\256\306\377\261=\237P^\223Su\202!\375\224?\320T\v\365\265\200\263\241"..., 4096) = 328
read(89, "\0\0\0 \237\247\rj \241\333\241\2704\250\250 \314L!{V\224\265\2579L\20`\331\331D"..., 4096) = 68
read(89, "\0\0\0\220q\264\251\336d\251\20\227\376\v\0225\324Tb\301\254\243\36k~'\23\356J\1\237S"..., 4096) = 344
read(89, "\0\0\0\200\231\35+\221\302\201\321T\364\364\360j\203\373P$\317\350p\362\361/\336\215\3140Cu"..., 4096) = 164
read(89, "\0\0\0 \327\254\205E\311\210\232\317\247\254\340\263LyM\25\21\365\32\235\251\316\25\237\252\267\245\303"..., 4096)= 68
read(89, "\0\0\0\220\207\16\23\177\360[d\253\347\31g\30\212R:\23\365\31\263\236u)\326\276\37\360\32\200"..., 4096) = 360
read(89, "\0\0\0 l\234\241\22\256r\235\345g\306\4\203\361E\3632EEY4\262\22\235/\322\320\232\2"..., 4096) = 68
read(89, "\0\0\0\220\252|\236V\303\334\256dL\325C\261\371rjE\200\253\300\333W\16H\306\207\342%4"..., 4096) = 180
read(89, "\0\0\0\200q\3126\\\275U\\\271'\272\200\f\304\3749\232p\325\355\31GCnSp\220\377\307"..., 4096) = 164
read(89, "\0\0\0\200&\2220,\336K\202\375\361\310\"\213l\257\0236\250\3632\r\221b?\325\4\216\303\351"..., 4096) = 328
read(89, "\0\0\0 vf\33M\373\327$\224\24T\354\343;\272\372)>^\335\346\221$\274\366v\222\25j"..., 4096) = 232
read(89, "\0\0\0\200\316~\341\375\217\300\3745$9\340\371L\357\222\1\226\245\333\261\335w\342\223&\343\354#"..., 4096) = 164
futex(0x191f188, FUTEX_WAIT_PRIVATE, 0, NULL  停在这里一直不动了请参考

**Comment by zhouyuyong** [comment]
@LeeEirc 
1.5.4 遇到同样问题,在cpu异常时 使用strace追踪进程，如下
futex(0x191f188, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
read(89, "\0\0\0@\\217\207\fs\251\373\347\230\252}\273\10\222vY\177\220\262\272\376v\200\363-\305\227\4"..., 4096) = 336
read(89, "\0\0\0\200JB\365\333\314\320\207\4"x}W\236\272\323\\nJ\323\224D\221\312\363\241[\272\f"..., 4096) = 232
read(89, "\0\0\0\200\265\2?$-\345\255\202;1\35o|\n\2\n\274\256\v\313\322Qt\333]k\230\336"..., 4096) = 232
read(89, "\0\0\0p\21\265\246\10{\334!g\0201\352\300P\225\213P\213!\331\203w\31e\375\261\275H"..., 4096) = 216
read(89, "\0\0\0\200K\343m)\201\32\4x-\215\331\260\263f\32\336\23[\314\355\344\332\211<!e:\237"..., 4096) = 232
read(89, "\0\0\0\200\216R\35\0106\313\260\213\f\263\363C]\277\30\rP\276bS\321x\236\373\5@\271\23"..., 4096) = 164
read(89, "\0\0\0\220\365\307\262OOpE\222\244\247\366p\310XoC\342\23\254W\247\2j\203g0=X"..., 4096) = 180
read(89, 0xc000d1c000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
write(89, "\0\0\0\20bqm\317\r\243\253\30\340\25\nX\365\26C\303\206\25253\273\223&\350\34>\17\16"..., 52) = 52
epoll_pwait(6, {{EPOLLIN|EPOLLOUT, {u32=187457088, u64=140157855227456}}}, 128, 0, NULL) = 1
read(89, "\0\0\0010\232V\247\346\24\366\364f\237\210\251\256i\203W\374\360\372\211\300\305\201Vh\275\317\n-"..., 4096) = 408
read(89, "\0\0\1\0X\321\345\2ByIy"]\271\3\352\343\37\367\f\246pQ#\256O\310\263\262\343;"..., 4096) = 292
read(89, "\0\0\0\200\252\211\325:\304\251\277M\206\22\27\344cb\240h\371\227[Z\v<\235\3\312\35Bu"..., 4096) = 164
read(89, 0xc000d1c000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
epoll_pwait(6, {{EPOLLIN|EPOLLOUT, {u32=187457088, u64=140157855227456}}}, 128, 0, NULL) = 1
read(89, "\0\0\0\320\343\203o}D\350\n\34\306\226\331\3\371\377\223\342\352\255X\243*\267+\302\34\1sB"..., 4096) = 244
read(89, "\0\0\0\200lg\\17\222\255\f\332\36\332l\300\330\216\r{\2\214a\5\262\354\327\264\v\16\214+"..., 4096) = 328
read(89, "\0\0\0\220;\242'z\30\203\335}\350\235S\tZv\347\34\242\21\25I2\251\\17!#b\215"..., 4096) = 180
read(89, "\0\0\0 \5\217\241\361X\351F\36\264\236\223(|kg'\5\250\364\335\353\237{\267\366\272i\354"..., 4096) = 68
read(89, "\0\0\0\200\254\330Y\340\256\306\377\261=\237P^\223Su\202!\375\224?\320T\v\365\265\200\263\241"..., 4096) = 328
read(89, "\0\0\0 \237\247\rj \241\333\241\2704\250\250 \314L!{V\224\265\2579L\20`\331\331D"..., 4096) = 68
read(89, "\0\0\0\220q\264\251\336d\251\20\227\376\v\0225\324Tb\301\254\243\36k'\23\356J\1\237S"..., 4096) = 344
read(89, "\0\0\0\200\231\35+\221\302\201\321T\364\364\360j\203\373P$\317\350p\362\361/\336\215\3140Cu"..., 4096) = 164
read(89, "\0\0\0 \327\254\205E\311\210\232\317\247\254\340\263LyM\25\21\365\32\235\251\316\25\237\252\267\245\303"..., 4096)= 68
read(89, "\0\0\0\220\207\16\23\177\360[d\253\347\31g\30\212R:\23\365\31\263\236u)\326\276\37\360\32\200"..., 4096) = 360
read(89, "\0\0\0 l\234\241\22\256r\235\345g\306\4\203\361E\3632EEY4\262\22\235/\322\320\232\2"..., 4096) = 68
read(89, "\0\0\0\220\252|\236V\303\334\256dL\325C\261\371rjE\200\253\300\333W\16H\306\207\342%4"..., 4096) = 180
read(89, "\0\0\0\200q\3126\\275U\\271'\272\200\f\304\3749\232p\325\355\31GCnSp\220\377\307"..., 4096) = 164
read(89, "\0\0\0\200&\2220,\336K\202\375\361\310"\213l\257\0236\250\3632\r\221b?\325\4\216\303\351"..., 4096) = 328
read(89, "\0\0\0 vf\33M\373\327$\224\24T\354\343;\272\372)>^\335\346\221$\274\366v\222\25j"..., 4096) = 232
read(89, "\0\0\0\200\316~\341\375\217\300\3745$9\340\371L\357\222\1\226\245\333\261\335w\342\223&\343\354#"..., 4096) = 164
futex(0x191f188, FUTEX_WAIT_PRIVATE, 0, NULL 停在这里一直不动了请参考

**Comment by LeeEirc** [comment]
@zhouyuyong 使用最新的1.5.4或者最新的1.5.6版本。
