### ISSUE TITLE
ssh 终端主机名显示乱序以及部分体验反馈。

### ISSUE THREAD

**Issue by py0426** [jumpserver/koko#141]
![image](https://user-images.githubusercontent.com/32036991/68173165-0d5ef080-ffb5-11e9-8fb0-6938a90216f8.png)
1.图中，主机名并没有按照一定规则排序，在实际使用过程中，大多数都是按照主机名来进行查询。乱序的情况下加大了寻找机器的难度。
2.翻页按键能否增加几个比如 pageup,pagedown或者 游标左键和游标右键。
3.大多数人在进入终端后，会直接按回车直接进入了资产列表，能够在资产列表内除了支持 ID 登录外，支持主机名或者 ip 登录。

**Comment by LeeEirc** [comment]
1. 资产是按照主机名排序的，正如图中所示A-Z
2. 暂不支持pageup、pagedown等按键操作
3. 输入 部分IP、主机名、备注 进行搜索登录(如果唯一)，可按照欢迎页面提示进行操作。

**Comment by LeeEirc** [comment]
@py0426 最新1.5.6支持多次搜索，可以在资产列表页面进行操作。
