### ISSUE TITLE
koko 是否向下兼容1.4.8 版本得jumpserver

### ISSUE THREAD

**Issue by wolfguoliang** [jumpserver/koko#149]
启动得时候提示如下错误，谢谢！
POST http://IP:8080/api/v2/terminal/terminal-registrations/ failed, get code: 404, <h1>Not Found</h1><p>The requested resource was not found on this server.</p>

**Comment by LeeEirc** [comment]
@wolfguoliang koko暂不向下兼容，请保持各版本组件一致。

**Comment by wolfguoliang** [comment]
好的，十分感谢。
