### ISSUE TITLE
koko的CPU消耗非常高，web终端连接卡顿；

### ISSUE THREAD

**Issue by l-duan** [jumpserver/koko#15]
![图片](https://user-images.githubusercontent.com/12080822/60081417-4a43ec80-9764-11e9-8578-2c76abdc5210.png)
4core8GB的云主机，不知道是不是有什么别的配置？
perf查看进程cpu消耗：
![图片](https://user-images.githubusercontent.com/12080822/60081574-a3ac1b80-9764-11e9-9b29-44a3786969ae.png)

docker_jms的日志，没有看出啥问题。
![图片](https://user-images.githubusercontent.com/12080822/60081534-89723d80-9764-11e9-9bb6-e28d819f9b85.png)

**Comment by LeeEirc** [comment]
cpu消耗，是因为同时打开很多连接吗？ @l-duan

**Comment by l-duan** [comment]
> 
> 
> cpu消耗，是因为同时打开很多连接吗？ @l-duan

是4core8GB的云主机，同时在线有25个session，不知道这个算不算多。之前用coco是没有这个问题的

**Comment by Daniel777777** [comment]
和老哥问题一样。版本问题导致的话，请先给一个临时回退的方案，已经影响生产使用了

**Comment by LeeEirc** [comment]
@l-duan  还能提供更多信息吗? 暂时无法复现问题。

**Comment by l-duan** [comment]
> 
> 
> @l-duan 还能提供更多信息吗? 暂时无法复现问题。
刚刚已经远程查看过了。

**Comment by l-duan** [comment]
> 
> 
> @l-duan 还能提供更多信息吗? 暂时无法复现问题。

有预估多长时间可以修复么

**Comment by Daniel777777** [comment]
1.5.1 新版本能否修复这个koko的BUG？

**Comment by youlinux** [comment]
同样 新安装的也出现这个问题 该docker容器会经常无缘无故的死掉,并且CPU占用一直100%

**Comment by LeeEirc** [comment]
> 同样 新安装的也出现这个问题 该docker容器会经常无缘无故的死掉,并且CPU占用一直100%

如果docker容器无辜死掉，有异常日志吗？

**Comment by youlinux** [comment]
您好  应该是下面这个 如图。 好像是在传文件的时候会发生。
![image](https://user-images.githubusercontent.com/28828034/60798792-6ef88500-a1a4-11e9-9f9c-dbcba2e5ddc1.png)

**Comment by youlinux** [comment]
![image](https://user-images.githubusercontent.com/28828034/60800138-3908d000-a1a7-11e9-847f-fd7f9788ba23.png)

**Comment by LeeEirc** [comment]
@youlinux 看着不是最新的代码，请删除旧镜像，使用最新的镜像试试。

**Comment by youlinux** [comment]
好的  多谢 我试试~

**Comment by Daniel777777** [comment]
> @youlinux看着不是最新的代码，请删除旧镜像，使用最新的镜像试试。

请问新版本修复了koko cpu很高的问题吗？

**Comment by ibuler** [comment]
perf的命令是什么呢？我们看看

**Comment by ibuler** [comment]
我部署到容器了，perf top看不到哪一行， @l-duan

**Comment by LeeEirc** [comment]
@l-duan @Daniel777777 已经优化代码，可避免cpu高问题。
