### ISSUE TITLE
Access role is not App 

### ISSUE THREAD

**Issue by liuhaogui** [jumpserver/koko#162]
jumpserver默认无App角色组，使用koko提示不能使用Admin角色组如何考虑的呢？

方法： validateAccessAuth

**Comment by LeeEirc** [comment]
基于数据安全的考虑。koko通常都是自动注册成app的。不知道你的koko为什么会是Admin的角色，且为什么要使用admin角色组？

**Comment by st8350** [comment]
如果是分布式部署的话，另外起的koko进程需要向core内注册，accesskey需要如何获取？

**Comment by st8350** [comment]
@LeeEirc 如果是分布式部署的话，另外起的koko进程需要向core内注册，accesskey需要如何获取？
