### ISSUE TITLE
koko生产环境cpu吃满，coco不曾出现，已经影响生产使用

### ISSUE THREAD

**Issue by Daniel777777** [jumpserver/koko#17]
![image](https://user-images.githubusercontent.com/31091714/60103640-8e4de600-9792-11e9-8cbb-a083e3bef52c.png)
![image](https://user-images.githubusercontent.com/31091714/60103727-b0476880-9792-11e9-98b0-c584a437d30c.png)

**Comment by ibuler** [comment]
可以继续使用   python 版本coco

**Comment by Daniel777777** [comment]
koko停掉了，然后重新下了一个coco，启动的时候 一直报access key找不到。

**Comment by youlinux** [comment]
替换 koko使用 coco 一直提示  " 资产 临时服务器1 不包含系统用户 测试 协议 ssh "   换回koko是好的。。请问这个是什么问题啊。。

**Comment by ibuler** [comment]
已处理
