### ISSUE TITLE
koko 自定义显示字段功能

### ISSUE THREAD

**Issue by junly917** [jumpserver/koko#173]
koko 里面如何添加显示字段？ 没有自定义显示哪些字段功能？
现需要添加显示label字段，如何来做？有没有计划添加此功能？
![image](https://user-images.githubusercontent.com/16676780/70590446-afee3d00-1c0d-11ea-99d7-0769dce17de8.png)

**Comment by LeeEirc** [comment]
目前没有自定义显示，你希望增加哪些label字段？

**Comment by junly917** [comment]
每台主机不是可以设置多个标签吗？ 能显示这些标签吗？ 
有时间这个主机配置了机房、机架位置、跑的服务啥的， 最好还可以使用搜索功能，搜索这些标签

**Comment by LeeEirc** [comment]
koko没有获取资产的标签，暂时无法显示标签。

**Comment by junly917** [comment]
后续是否有添加此类的功能？ 有没有考虑过可以让用户自定义增、删除字段了？

**Comment by LeeEirc** [comment]
暂且没有这方面的计划。
