### ISSUE TITLE
bytesToKey方法很耗CPU

### ISSUE THREAD

**Issue by jasper-zhang** [jumpserver/koko#176]
我们线上的koko把机器的CPU打满了，通过pprof看了下，主要的消耗在bytesToKey函数上：
![image](https://user-images.githubusercontent.com/6657098/70788603-3486ba00-1dcc-11ea-9be7-1853c213035e.png)

再细看了下这个函数，发现消耗最大的代码在如下一段：
![image](https://user-images.githubusercontent.com/6657098/70788700-66981c00-1dcc-11ea-9fce-7ce874f57e7f.png)

想问一下这段代码的作用是什么(我没太看懂)？还有是否可以优化呢？

**Comment by LeeEirc** [comment]
你们用的哪一个版本的koko？

**Comment by jasper-zhang** [comment]
用的1.5.1

**Comment by LeeEirc** [comment]
@jasper-zhang 升级一下版本吧，新版本有对引起cpu高的问题做优化。

**Comment by jasper-zhang** [comment]
@LeeEirc 我们做了很多二次开发，升级版本会麻烦一些，能给下优化的commit么，我们照着优化一下

**Comment by LeeEirc** [comment]
可参照1.5.2的相关更改。

**Comment by jasper-zhang** [comment]
我看了下我上面贴的耗cpu的地方还是没动的嘛，难道消耗不在这里？

**Comment by zhuxingtao** [comment]
1.5.5cpu还是耗得多

**Comment by LeeEirc** [comment]
@jasper-zhang 使用最新的1.5.2版本吧。 @zhuxingtao 使用最新的1.5.6版本。

**Comment by naivelife** [comment]
1.5.6对cpu的优化主要是体现在哪里呢？
