### ISSUE TITLE
通过sftp从服务器下载文件到本地有大概率文件不全

### ISSUE THREAD

**Issue by qiuDar** [jumpserver/koko#182]
如题，使用sftp软件(xftp)从服务器上下载文件到本地时至少有30%的概率出现文件不全。手头上一共有4台jms服务器，每一台都进行过测试，都存在相同的问题。同时也尝试使用其他软件，如winscp，也存在同样的问题，但是通过jumpserver的websftp下载文件没任何异常，这个问题从koko创建至今一直存在。
![image](https://user-images.githubusercontent.com/10934817/71389282-b8476e80-2636-11ea-8608-27e0cf00425f.png)
![image](https://user-images.githubusercontent.com/10934817/71389293-c6958a80-2636-11ea-92d3-56fd6e2a7181.png)

**Comment by ibuler** [comment]
@LeeEirc

**Comment by LeeEirc** [comment]
@qiuDar 正在尝试复现，提供一下你测试使用的版本。

**Comment by qiuDar** [comment]
> @qiuDar 正在尝试复现，提供一下你测试使用的版本。

测试使用的版本是1.5.5，今天更新1.5.6之后测试依然存在这个问题，具体表现为：使用sftp软件如xftp或者winscp通过koko从服务器下载文件，下载成功后有概率出现文件不全，比如zip大小不对，打开提示损坏，php文件大小不对，文件内丢失一部分内容。

**Comment by LeeEirc** [comment]
@qiuDar 加我qq 2970298425，我远程帮你看下。

**Comment by LeeEirc** [comment]
已经修复，使用最新的master。
