### ISSUE TITLE
1.5.5版本的koko web终端无法连接资源

### ISSUE THREAD

**Issue by kentwanwan** [jumpserver/koko#187]
ssh方式连资产正常。
web终端连接资产时无任何反应。
![深度截图_选择区域_20191227140144](https://user-images.githubusercontent.com/49065202/71503745-9279ce00-28b1-11ea-852b-8650586d72f5.png)

**Comment by LeeEirc** [comment]
@kentwanwan 核实一下nginx的配置是否正确，需要添加上支持websocket的配置

**Comment by kentwanwan** [comment]
是nginx的配置问题，之前的配置与后面版本的有冲突的地方。
