### ISSUE TITLE
luna连接上资产后，输入中文出现不响应

### ISSUE THREAD

**Issue by glkappe** [jumpserver/koko#19]
版本都是1.5.0

完全按照 安装：
https://jumpserver.readthedocs.io/zh/master/setup_by_centos7.html

os：CentOS Linux release 7.6.1810 (Core) 

问题：
luna输入中文，luna没反应

相关报错截图：
Nginx配置和文档一致

jumpserver.conf和文档一致

chrome报错：
![image](https://user-images.githubusercontent.com/21033020/60417431-03963c80-9c13-11e9-8a53-90be6acb843f.png)

koko日志：
![image](https://user-images.githubusercontent.com/21033020/60417272-98e50100-9c12-11e9-8288-0ece4e485007.png)

真心求助。

**Comment by ibuler** [comment]
无法复现，这个问题还存在吗
