### ISSUE TITLE
Goland 远程用delve调试koko不成功，本地windows 调试，go build koko.go 报错

### ISSUE THREAD

**Issue by cw4t** [jumpserver/koko#195]
本地Windows go build koko.go 报错：
undefined: syscall.Stat_t

或者您能帮我进行server 远程调试吗？通过delve

求助，已经搞了这几天了

**Comment by LeeEirc** [comment]
koko暂且不支持windows的编译

**Comment by cw4t** [comment]
好，linux远程成功了谢谢发自我的iPhone------------------ 原始邮件 ------------------发件人: Eric_Lee  <notifications@github.com>发送时间: 2020年1月14日 10:36收件人: jumpserver/koko <koko@noreply.github.com>抄送: cw4t <chasewater4truth@gmail.com>, Author <author@noreply.github.com>主题: 回复：[jumpserver/koko] Goland 远程用delve调试koko不成功，本地windows 调试，go build koko.go 报错 (#195)Closed #195.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jumpserver/koko/issues/195?email_source=notifications\u0026email_token=ADSVS6UCNKGEVXI6IEWQG6DQ5UQKVA5CNFSM4KETKUA2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOV6IFXKA#event-2945473448",
"url": "https://github.com/jumpserver/koko/issues/195?email_source=notifications\u0026email_token=ADSVS6UCNKGEVXI6IEWQG6DQ5UQKVA5CNFSM4KETKUA2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOV6IFXKA#event-2945473448",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
