### ISSUE TITLE
通过koko的sftp传输文件后损坏

### ISSUE THREAD

**Issue by linuxu2015** [jumpserver/koko#2]
1、jumpserver版本：
1.5.0
2、koko部署方式
docker和编译都有
3、现象：
使用filezilla配置后，上传tar.gz格式文件后，提示传输成功，网页上的ftp审计日志也显示成功，在服务器上使用tar命令解压后，提示错误。
![image](https://user-images.githubusercontent.com/12248480/59663970-bbbef080-91e2-11e9-8fd8-763700fded94.png)
另外上传前后文件的md5值不相同。
同样的，在服务器上新打一个tar.gz的压缩包，通过sftp下载后，使用windows的7zip解压软件打开提示数据错误。
以上文件通过直连上传和下载均无问题。

**Comment by LeeEirc** [comment]
已修复
