### ISSUE TITLE
make linux 时出现以下错误

### ISSUE THREAD

**Issue by cw4t** [jumpserver/koko#203]
(jmp) [saicops@VM_10_160_centos cmd]$ make linux
fatal: Not a git repository (or any of the parent directories): .git
cp -r locale static templates config_example.yml kokodir
编译 linux
GOOS=linux GOARCH=amd64 go build -o koko koko.go
# github.com/jumpserver/koko/pkg/config
../pkg/config/config.go:62:9: undefined: yaml
../pkg/config/config.go:95:18: undefined: yaml
make: *** [linux] Error 2

**Comment by LeeEirc** [comment]
@cw4t 你的go环境可能没有配置正确

**Comment by cw4t** [comment]
> @cw4t 你的go环境可能没有配置正确

[saicops@VM_10_160_centos build]$ go version
go version go1.13.4 linux/amd64
[saicops@VM_10_160_centos build]$ echo $GOPATH
/home/saicops/.go
[saicops@VM_10_160_centos build]$ echo $GOROOT
/opt/soft_ln/go
[saicops@VM_10_160_centos build]$ which go
/opt/soft_ln/go/bin/go

以前都可以的啊，今天突然不行了。

**Comment by LeeEirc** [comment]
@cw4t koko目前使用go语言的1.12版本

**Comment by cw4t** [comment]
不过现在用1.13.4也可以，希望后面Koko添加使用的Go具体版本，谢谢
