### ISSUE TITLE
windows sftp 进去的路径不对，配置的是SFTP_ROOT: home

### ISSUE THREAD

**Issue by cw4t** [jumpserver/koko#216]
如题，Windows 的sftp 登录进去路径不对，是 /[windowsservername], Linux对的，是/home/[username]

**Comment by LeeEirc** [comment]
@cw4t windows的sftp server，你使用xftp等工具连接的默认home目录是什么？

**Comment by cw4t** [comment]
> @cw4t windows的sftp server，你使用xftp等工具连接的默认home目录是什么？

xrdp? xrdp 不是远程桌面嘛，什么home目录？

**Comment by cw4t** [comment]
func (fs *sftpHandler) Filelist(r *sftp.Request) (sftp.ListerAt, error) {
	switch r.Method {
	case "List":
		logger.Debug("List method: ", r.Filepath)
		res, err := fs.ReadDir(r.Filepath)   // ReadDir 结果: res为空。
		fileInfos := make(listerat, 0, len(res))

这个是pkg/handler/sftp.go 里面的Filelist 函数里的断点调试，这里res为空。

**Comment by cw4t** [comment]
![22](https://user-images.githubusercontent.com/15030650/72498203-9b830d00-3869-11ea-94c0-144687df1ce3.PNG)
路径不对

**Comment by cw4t** [comment]
o 是 xftp ， 我用的winscp 登进去的，路径这边没打印出来。。linux打印出来了
![11](https://user-images.githubusercontent.com/15030650/72499025-b9ea0800-386b-11ea-9ad9-17928b76eef4.PNG)

**Comment by cw4t** [comment]
断电打印在： pkg/srvconn/sftpconn.go 里的函数GetSFTPAndRealPath 这里
func (u *UserSftp) GetSFTPAndRealPath(req requestMessage) (conn *SftpConn, realPath string) {
	fmt.Printf("req: %s, %s, %s, %s", req.dpath, req.host, req.su, req.suUnique)
	if host, ok := u.hosts[req.host]; ok {
		if su, ok := host.suMaps[req.su]; ok {
			key := fmt.Sprintf("%s@%s", su.Name, req.host)
			conn, ok := u.sftpClients[key]
			logger.Info("++++ Enter GetSFTPAndRealPath func+++")
			if !ok {
				var err error
				conn, err = u.GetSftpClient(host.asset, su)
				if err != nil {
					logger.Debug("Get Sftp Client err: ", err.Error())
					return nil, ""
				}
				u.sftpClients[key] = conn
			}

			switch strings.ToLower(u.RootPath) {
			case "home", "~", "":
				realPath = filepath.Join(conn.HomeDirPath, strings.TrimPrefix(req.dpath, "/"))
			default:
				realPath = filepath.Join(u.RootPath, strings.TrimPrefix(req.dpath, "/"))
			}
			logger.Infof("--------- realPath is %s", realPath)
			return conn, realPath
		}
	}

**Comment by cw4t** [comment]
windows竟然没有进来这个函数。。

**Comment by LeeEirc** [comment]
@cw4t 你Windows sftp server，怎么配置的？直接使用winscp登录你windwos的sftp server，不走koko，看一下home目录是否正确。

**Comment by cw4t** [comment]
直接等录是home目录：
![捕获](https://user-images.githubusercontent.com/15030650/72501660-5adbc180-3872-11ea-99b9-c579aa769aa7.PNG)

**Comment by cw4t** [comment]
![捕获](https://user-images.githubusercontent.com/15030650/72503556-f40cd700-3876-11ea-9211-64e4f8dd21ec.PNG)

**Comment by LeeEirc** [comment]
@cw4t 加我qq吧，远程看下2970298425

**Comment by cw4t** [comment]
我们公司不能远程 笑哭

**Comment by cw4t** [comment]
安全限制，qq 远程， teamviewer都被禁止

**Comment by cw4t** [comment]
原来是我之前改了配置项， 忘记改回去了，可是由于Config.go等中间层的默认配置项，没有报错。以至于搞了很久。。。
