### ISSUE TITLE
桥接时srvConn读取部分控制符异常

### ISSUE THREAD

**Issue by byteswift** [jumpserver/koko#226]
在Terminal输入方向左键，LoopRead函数从userConn读取字节流，并将读取的数据写入通道userInChan，ParseStream函数解析用户输入数据流，将解析后的数据发送至通道userOutChan；在Bridge函数里，接收来自userOutChan的字节流，并将其写入srvConn。此时，向srvConn写入的字节流数据为[27 91 68]；但是，LoopRead函数从srvConn读取数据时，读取到的字节流却是[8]。如下所示：
![image](https://user-images.githubusercontent.com/48037998/72708227-38f97c00-3b9d-11ea-9eaf-e7c3ebf2b1ec.png)
srvInChan通道接收到的数据写入srvConn的数据不一致，那么在函数ParseServerOutput中往cmdInputParser写入的数据不正确，经bytesToKey函数，会将左键视作Backspace键处理，就会导致Parser.command中存储的命令与实际写入srvConn的命令不一致，而对命令过滤时是用command与过滤规则去匹配，因此执行命令时可以使用左键绕开命令过滤机制，有很大的安全隐患。

**Comment by LeeEirc** [comment]
命令过滤已经完成一次优化，请使用v2.7.0验证，有问题再反馈。
