### ISSUE TITLE
一直有不明的连接在请求我的jumpserver

### ISSUE THREAD

**Issue by php-cpm** [jumpserver/koko#232]
hi，我用jumpserver一段时间了，通过日志审计->登录日志发现大量登录失败日志。来自世界各地。

testuser | Terminal | koko-client | 47.56.187.161 | 香港 中国 | - | 用户名/密码 校验失败 | 失败 | 2020年2月16日 09:09

我google 关键字 koko-client找到这里，请问是有什么故障吗？如何防止。

**Comment by LeeEirc** [comment]
这只显示有人尝试登录而已，与尝试登录web页面是类似的情况，不存在故障。ssh 工具登录 Jumpserver 连接的是 Koko 组件，如果你不希望如 xshell 等 ssh 工具方式登录，可以不开放默认的2222端口。
