### ISSUE TITLE
客户端登录怎么禁用密码登录

### ISSUE THREAD

**Issue by wqk151** [jumpserver/koko#236]
您好，请问下：
1、通过客户端如xshell登录时，能否设置禁用密码登录，只支持密码登录？
2、生成秘钥能否设置密码？

**Comment by LeeEirc** [comment]
![image](https://user-images.githubusercontent.com/32626707/75643120-e79edb00-5c78-11ea-8c5d-2b08c989d14c.png)
这里设置了koko终端使用的认证方式
