### ISSUE TITLE
新版本不支持主机查询保持

### ISSUE THREAD

**Issue by stayhungry001** [jumpserver/koko#239]
老版本coco可以在输入关键字之后，登录主机退出，继续直接使用索引直接进入另一台主机。而新版本的koko则需要重新查询在进入其他主机。感觉这个功能挺方便的，是否可以落地。

**Comment by ibuler** [comment]
@LeeEirc 维护context

**Comment by stayhungry001** [comment]
主机加载测试改成非all。
