### ISSUE TITLE
输入命令后，连续输入多个 Enter，第一条命令无法记录

### ISSUE THREAD

**Issue by xf0rk** [jumpserver/koko#24]
RT，输入一条命令 A 后，立即连续输入多个 Enter，导致输入的命令 A 无法记录

https://github.com/jumpserver/koko/blob/0ac28fdaca60f97219c396173108c5620767d8c5/pkg/proxy/parser.go#L118

**Comment by LeeEirc** [comment]
@xf0rk 已修复
