### ISSUE TITLE
JumpServer搭建后无法查询到用户列表

### ISSUE THREAD

**Issue by xiamengyou** [jumpserver/koko#245]
搭建了JumpServer后无法查询到用户列表和资产树，同时也无法创建用户。
点击创建用户时，控制台报错TypeError: form.serializeObject is not a function

**Comment by LeeEirc** [comment]
@xiamengyou 再核查一下是否正确部署，用使用最新的版本试一下。

**Comment by xiamengyou** [comment]
抱歉，是在Firefox39.0版本上进行了测试，在Firefox浏览器上不支持用户列表查询，用户新增，可能和浏览器不支持相关，切换到chrome浏览器之后一切正常发自我的华为手机-------- 原始邮件 --------发件人： Eric_Lee <notifications@github.com>日期： 2020年3月27日周五 16:25收件人： jumpserver/koko <koko@noreply.github.com>抄送： xiamengyou <2862452398@qq.com>, Mention <mention@noreply.github.com>主    题： Re: [jumpserver/koko] JumpServer搭建后无法查询到用户列表 (#245)

@xiamengyou 再核查一下是否正确部署，用使用最新的版本试一下。
