### ISSUE TITLE
Jumpserver到网域网关的连接未释放。

### ISSUE THREAD

**Issue by stayhungry001** [jumpserver/koko#264]
koko到网域网管连接未释放，导致koko的产生大量的连接。

**Comment by LeeEirc** [comment]
使用的是最新的1.5.7吗？

**Comment by stayhungry001** [comment]
刚刚拉的coco容器镜像，应该是最新的。是否有办法确认。

**Comment by LeeEirc** [comment]
`./koko -V`

**Comment by stayhungry001** [comment]
[root@d1ffc2c7b7b5 koko]# ./koko -V
Version:             1.5.7
Git Commit Hash:     8d65ca5171e470681605d782bf9e4ee0c7eec35f
UTC Build Time :     2020-03-20 10:43:19AM
Go Version:          go version go1.12 darwin/amd64

**Comment by LeeEirc** [comment]
@stayhungry001 更新了，使用最新的版本试试。
