### ISSUE TITLE
版本1.5.7 8d65ca5171e470681605d782bf9e4ee0c7eec35f  koko经常假死

### ISSUE THREAD

**Issue by quxf2012** [jumpserver/koko#265]
经常出现选完主机后,一直hang着不能进入系统. 每次需要重启koko.
2020-04-13 03:48:19 [ERRO] Logout event: ws ab29a565-abd5-48c4-8779-7ba4e79b7ecd could not found or already closed
2020-04-13 03:48:21 [ERRO] Logout event: ws ab29a565-abd5-48c4-8779-7ba4e79b7ecd could not found or already closed
2020-04-13 03:48:21 [ERRO] Logout event: ws ab29a565-abd5-48c4-8779-7ba4e79b7ecd could not found or already closed
2020-04-13 03:48:28 [ERRO] websocket ab29a565-abd5-48c4-8779-7ba4e79b7ecd could not found or alread closed

**Comment by LeeEirc** [comment]
@quxf2012 刷新页面也无法进入系统吗？命令行无法进入koko吗？

**Comment by quxf2012** [comment]
web和命令行都不可以进入,表现一样的.

**Comment by LeeEirc** [comment]
@quxf2012 使用最新master 自己build一个版本试试。

**Comment by LeeEirc** [comment]
@quxf2012 最近还出现吗？加我q 2970298425, 远程看下。

**Comment by quxf2012** [comment]
你好,上次按你说的编译最新master后,暂时没有出现了.

**Comment by joyexpr** [comment]
我也是经常碰到，昨天升级到1.5.8后，还是会出现

**Comment by LeeEirc** [comment]
@joyexpr 可以详细说下你遇到的情况吗？

**Comment by joyexpr** [comment]
一开始安装的是wojiushixiaobai的docker-compose 1.5.7版本，在选择完机器和用户后就卡住不动了，需要docker restart koko容器才能恢复正常。昨晚试了下升级1.5.8，今天早上又出现这种情况

koko.log里看了主要有3种类型报错：
1、 [ERRO] User root Authenticate err: POST http://core:8080/api/v1/authentication/tokens/ failed, get code: 400, {"error":"password_failed","msg":"您输入的用户名或密码不正确，请重新输入。 您还可以尝试 5 次（账号将被临时 锁定 30 分钟）"}

2、[ERRO] User xxx did not found cache ssh client

3、[ERRO] Request d9ef7b13-8846-41ef-b28f-2ca8477100c7: Send user xxx keepalive packet failed: EOF

我一度怀疑是同事使用了web终端或它使用的securecrt工具触发，暂时未确认

**Comment by LeeEirc** [comment]
@joyexpr 感谢反馈，这些信息都是正常的日志错误。尽量看下是否可以用什么方式能够复现。也可以加我q 2970298425交流下。

**Comment by joyexpr** [comment]
@LeeEirc 我再观察下

**Comment by Egi0lg** [comment]
在1.5.8 上最近也遇到了同样的报错，只要通过 jumpserver 连接就会报 `[ERRO] User xxx did not found cache ssh client(root@hostname)`，但不是卡住，而是连接时间很长大概需要2~3s左右，不清楚这两者是否有因果关系，而我直接在jumpserver所在设备连接目标设备是很快的1s以内，jumpserver中所有的设备都有连接慢的这个问题。

抓包看是 server 回包慢导致的连接时长变长
![image](https://user-images.githubusercontent.com/8529400/89151907-887d2380-d594-11ea-8203-033f1a8282ae.png)

然后我用 strace 追踪 ssh 进程，获得以下信息：(有2s的时间差，跟抓包不是同一次连接，所以时间差上有差异）
`[pid 23067] 11:43:14.349722 sendto(4, "<85>Aug  3 11:43:14 sshd[23067]:"..., 143, MSG_NOSIGNAL, NULL, 0) = 143`
`[pid 23067] 11:43:14.349776 select(0, NULL, NULL, NULL, {tv_sec=2, tv_usec=5660}) = 0 (Timeout)`
`[pid 23067] 11:43:16.357586 socket(AF_NETLINK, SOCK_RAW, NETLINK_AUDIT) = 8`
`[pid 23067] 11:43:16.357680 fcntl(8, F_SETFD, FD_CLOEXEC) = 0`

被连接端找不出其它信息了，所以想看看是不是 jumpserver 这头的问题？ @LeeEirc 谢谢！

koko.log 中也有 @joyexpr 提到的其它2个问题

**Comment by LeeEirc** [comment]
> 只要通过 jumpserver 连接就会报 `[ERRO] User xxx did not found cache ssh client(root@hostname)`，

这是一条正常的日志信息，可以忽略。ssh连接慢，可能有存在多个方面，可使用最新的 v2.3.0 体验下，已经优化web端的连接。
