### ISSUE TITLE
1.5.6 版本koko 大文件 sftp 传输出错

### ISSUE THREAD

**Issue by cw4t** [jumpserver/koko#281]
![QQ图片20200423105535](https://user-images.githubusercontent.com/15030650/80054113-0622a380-8551-11ea-90ba-d5724da3723f.png)
![QQ图片20200423105542](https://user-images.githubusercontent.com/15030650/80054115-07ec6700-8551-11ea-9773-10cfe83596e8.png)
如上图，上传和下载稍微大一点的文件就会出错。试了下，600KB 的文件上传下载就会出现问题

**Comment by LeeEirc** [comment]
使用最新版本。
