### ISSUE TITLE
1.5.6版本 Koko sftp 上传文件到Windows 服务器，打不开显示被Sftp-server进程占用

### ISSUE THREAD

**Issue by cw4t** [jumpserver/koko#282]
![image](https://user-images.githubusercontent.com/15030650/80088735-7fd98200-858f-11ea-9c7d-b548b3f555f1.png)
如上图，查看代码，是由于这一块：

`func (c *clientReadWritAt) WriteAt(p []byte, off int64) (n int, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.firstErr != nil {
		return 0, c.firstErr
	}
	_, _ = c.f.Seek(off, 0)
	nw, err := c.f.Write(p)
	if err != nil {
		c.firstErr = err
		_ = c.f.Close()
		return nw, err
	}
	return nw, err
}`

当 err == nil  正常写入时，没有在最后执行  c.f.Close()， 而只是在出异常时执行了Close

**Comment by cw4t** [comment]
func (c *clientReadWritAt) WriteAt(p []byte, off int64) (n int, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.firstErr != nil {
		return 0, c.firstErr
	}
	_, _ = c.f.Seek(off, 0)
	nw, err := c.f.Write(p)
	if err != nil {
		c.firstErr = err
		_ = c.f.Close()
		return nw, err
	}

    // 这里需要判断是否是文件末尾，是末尾则应该在 写入完毕后，执行 c.f.Close()
	return nw, err
}

**Comment by LeeEirc** [comment]
请使用最新的版本1.5.8版本
