### ISSUE TITLE
所有版本koko 都存在命令过滤可以绕过的情况

### ISSUE THREAD

**Issue by cw4t** [jumpserver/koko#284]
比如，禁止  rm -rf ， reboot, sz , rz
但是如果将这些命令写在 do.sh 里， 然后 sh do.sh ，就可以执行了

**可以绕过**

**Comment by npcomet** [comment]
是的 但不是 bug 你编译一个C的或者 go的 或者php的程序 传二进制上去 也无法限制你

过滤命令是避免在终端出现误操作 算是辅助手段

**Comment by cw4t** [comment]
我想在禁止sz/rz 即使在程序里也不能执行，之前有看到有打log，能在koko里实现嘛Chaserchasewater4truth@gmail.comSecurity Developer------------------ 原始邮件 ------------------发件人: yezhiqiu  <notifications@github.com>发送时间: 2020年8月4日 11:22收件人: jumpserver/koko <koko@noreply.github.com>抄送: cw4t <chasewater4truth@gmail.com>, Author <author@noreply.github.com>主题: 回复：[jumpserver/koko] 所有版本koko 都存在命令过滤可以绕过的情况 (#284)
是的 但不是 bug 你编译一个C的或者 go的 或者php的程序 传二进制上去 也无法限制你
过滤命令是避免在终端出现误操作 算是辅助手段

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jumpserver/koko/issues/284#issuecomment-668357696",
"url": "https://github.com/jumpserver/koko/issues/284#issuecomment-668357696",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by LeeEirc** [comment]
目前只拦截输入的命令。脚本等方式执行的命令，不支持拦截。
