### ISSUE TITLE
命令行过滤问题

### ISSUE THREAD

**Issue by stayhungry001** [jumpserver/koko#285]
1、当主机名包含命令黑名单字符，会显示命令被禁止
比如test-sz-001, 其中设置sz的命令是拒绝的情况下。会出现被禁止的情况；
2、当本应该是被拒绝的命令，命令行字符串包含Allow规则中的命令字符串时，即可绕过执行。
比如rm是允许的命令，mysql是拒绝的命令，但是执行mysql -h rm-xxxxxxx.aliyuncs.com时，即被允许。

**Comment by LeeEirc** [comment]
Koko是通过字符进行命令过滤和拦截，目前是最大限度的匹配，你可以通过写命令过滤正则来处理。
