### ISSUE TITLE
Weak SSH Hashing Algorithm and SSH Key Exchange Algorithms supported

### ISSUE THREAD

**Issue by claytonchew** [jumpserver/koko#290]
**We discovered a vulnerability reported from our scanner:**

Weak SSH Hashing Algorithm and SSH Key Exchange Algorithms supported on port 2222 JMS Koko service

**Evidence:**

1. Weak SSHv2 Key Exchange Algorithms: diffie-hellman-group1- sha1,diffie-hellman-group14-sha1
2. Weak SSHv2 MAC Algorithms Client to Server: hmac-sha1, hmac-sha1- 96

**Remediation Suggestions:**

1. Restrict the SSH service to no longer support weak hashing algorithms (aka: MACs).
2. Restrict the SSH service to no longer support weak key exchange algorithms (aka: KexAlgorithms).

**Comment by LeeEirc** [comment]
Thank you for your information. As we need support old devices, Koko would keep these algorithms.
