### ISSUE TITLE
koko  integer divide by zero

### ISSUE THREAD

**Issue by invincibluke** [jumpserver/koko#295]
koko 1.5.9 有严重BUG
通过docker ps jms_koko，会有如下报错，并重启docker
![image](https://user-images.githubusercontent.com/34088075/83372276-6e3d9280-a3f7-11ea-8444-d5306071e48d.png)

![image](https://user-images.githubusercontent.com/34088075/83372286-772e6400-a3f7-11ea-816e-491a68345dd3.png)

请@jumpserver 技术团队尽快解决，谢谢

**Comment by invincibluke** [comment]
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS              PORTS                                              NAMES
be009384d318        jumpserver/jms_koko:1.5.9        "./entrypoint.sh"   34 hours ago        Up 4 minutes        127.0.0.1:5000->5000/tcp, 0.0.0.0:5232->2222/tcp   jms_koko

**Comment by invincibluke** [comment]
panic: runtime error: integer divide by zero

goroutine 2987 [running]:
github.com/jumpserver/koko/pkg/handler.(*localDatabasePaginator).updatePageInfo(...)
	/Users/eric/Documents/fit2cloud/koko/pkg/handler/dbpaginator.go:161
github.com/jumpserver/koko/pkg/handler.(*localDatabasePaginator).retrievePageData(0xc0001cc7e0, 0x1, 0x0, 0x4, 0xc000248760)
	/Users/eric/Documents/fit2cloud/koko/pkg/handler/dbpaginator.go:153 +0x16f
github.com/jumpserver/koko/pkg/handler.(*localDatabasePaginator).RetrievePageData(0xc0001cc7e0, 0x1, 0x0, 0x0, 0x0)
	/Users/eric/Documents/fit2cloud/koko/pkg/handler/dbpaginator.go:110 +0x83
github.com/jumpserver/koko/pkg/handler.(*interactiveHandler).Dispatch(0xc0005e1340)
	/Users/eric/Documents/fit2cloud/koko/pkg/handler/dispatch.go:48 +0x8f0
github.com/jumpserver/koko/pkg/handler.SessionHandler(0x138dd20, 0xc000513200)
	/Users/eric/Documents/fit2cloud/koko/pkg/handler/session.go:34 +0x348
github.com/gliderlabs/ssh.(*session).handleRequests.func1(0xc000513200)
	/Users/eric/go/pkg/mod/github.com/ibuler/ssh@v0.1.6-0.20191022095544-d805cc9f27a8/session.go:235 +0x3b
created by github.com/gliderlabs/ssh.(*session).handleRequests
	/Users/eric/go/pkg/mod/github.com/ibuler/ssh@v0.1.6-0.20191022095544-d805cc9f27a8/session.go:234 +0x4cd
2020/06/01 10:58:15 Config file Path: config.yml
2020-06-01 10:58:15
Koko Version 1.5.9, more see https://www.jumpserver.org
Quit the server with CONTROL-C.

**Comment by LeeEirc** [comment]
请看这个回复[数据库分页问题](https://github.com/jumpserver/jumpserver/issues/4056#issuecomment-636591884)

**Comment by invincibluke** [comment]
> 请看这个回复[数据库分页问题](https://github.com/jumpserver/jumpserver/issues/4056#issuecomment-636591884)

感谢你，修改后，运行了30小时正常。
