### ISSUE TITLE
1.5.8 连接数据库应用失败

### ISSUE THREAD

**Issue by huangzx** [jumpserver/koko#296]
版本: 1.5.8 
提示如下：
xxxx's password:
连接数据库 mysql://mixdb.xxxx.ap-east-1.rds.amazonaws.com:2568/  0.0
Connect database mixdb.xxxx.ap-east-1.rds.amazonaws.com error: start local pty err: fork/exec /usr/bin/mysql: operation not permitted

**Comment by huangzx** [comment]
原来 koko 要用 root 来跑？
见代码:
![image](https://user-images.githubusercontent.com/3265516/83421032-ab367300-a451-11ea-8100-ffcb7efde2d5.png)

**Comment by LeeEirc** [comment]
需要使用root跑，且要有调用mysql的权限。
