### ISSUE TITLE
升级到koko，连接目标机器慢，基本都是10秒左右，旧版本的coco是很 快的 1秒左右

### ISSUE THREAD

**Issue by fengxinyuan** [jumpserver/koko#297]

**Comment by FrelDX** [comment]
https://github.com/FrelDX/kube-console-on-ssh

**Comment by FrelDX** [comment]
![image](https://user-images.githubusercontent.com/32826879/83704235-252e4e00-a644-11ea-8a91-1571139bdd1d.png)

**Comment by FrelDX** [comment]
Connect pod through SSH protocol

**Comment by LeeEirc** [comment]
@fengxinyuan 使用最新的版本。
