### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by glkappe** [jumpserver/koko#3]
(jumpserver_py3) [root@ser4-44 ~]# docker ps -a
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                     PORTS                              NAMES
948a56355e77        jumpserver/jms_koko:1.5.0        "./koko"            2 minutes ago       Exited (2) 2 seconds ago                                      jms_koko
fa6e25c7359e        jumpserver/jms_guacamole:1.5.0   "entrypoint.sh"     About an hour ago   Up About an hour           4822/tcp, 0.0.0.0:8081->8081/tcp   jms_guacamole

(jumpserver_py3) [root@ser4-44 ~]# docker logs 948a56355e77
2019-06-18 11:14:59
Coco version 1.5.0, more see https://www.jumpserver.org
Quit the server with CONTROL-C.
2019/06/18 11:15:09 http: superfluous response.WriteHeader call from github.com/jumpserver/koko/vendor/github.com/googollee/go-engine%2eio.(*Server).ServeHTTP (server.go:182)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x52daef]

goroutine 163 [running]:
regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, ...)
        /usr/local/go/src/regexp/exec.go:527 +0x6f
regexp.(*Regexp).FindString(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/regexp/regexp.go:786 +0xa9
github.com/jumpserver/koko/pkg/model.(*SystemUserFilterRule).Match(0xc000209cd0, 0x0, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/jumpserver/koko/pkg/model/assets.go:335 +0x51
github.com/jumpserver/koko/pkg/proxy.(*Parser).IsCommandForbidden(0xc0003de0c0, 0x1, 0x400, 0x1901242)
        /go/src/github.com/jumpserver/koko/pkg/proxy/parser.go:235 +0xfb
github.com/jumpserver/koko/pkg/proxy.(*Parser).parseInputState(0xc0003de0c0, 0xc00020c000, 0x1, 0x400, 0xc0000353e0, 0xc000017f08, 0xc0001be001)
        /go/src/github.com/jumpserver/koko/pkg/proxy/parser.go:123 +0x1d8
github.com/jumpserver/koko/pkg/proxy.(*Parser).ParseUserInput(0xc0003de0c0, 0xc00020c000, 0x1, 0x400, 0x1, 0x0, 0x0)
        /go/src/github.com/jumpserver/koko/pkg/proxy/parser.go:160 +0x82
github.com/jumpserver/koko/pkg/proxy.(*Parser).ParseStream(0xc0003de0c0)
        /go/src/github.com/jumpserver/koko/pkg/proxy/parser.go:98 +0x1ab
created by github.com/jumpserver/koko/pkg/proxy.(*SwitchSession).Bridge
        /go/src/github.com/jumpserver/koko/pkg/proxy/switch.go:136 +0x1f7

(jumpserver_py3) [root@ser4-44 ~]# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
jumpserver/jms_koko        1.5.0               317a789eac3a        3 hours ago         39.3MB
jumpserver/jms_guacamole   1.5.0               1bb99405b003        2 weeks ago         670MB

前端一操作 他就死掉 报错如上

**Comment by wojiushixiaobai** [comment]
@glkappe log看不出什么，把完整的log附上看看，jumpserver代码请更新到最新

**Comment by glkappe** [comment]
不会看jumpserver是什么版本 但是我有网页截图啊哈哈
![image](https://user-images.githubusercontent.com/21033020/59732051-48b58880-927b-11e9-87de-531533c7abc3.png)


koko日志如下：
![image](https://user-images.githubusercontent.com/21033020/59733220-b6fc4a00-927f-11e9-8eee-be5d89269e69.png)
奏一行

我刚把koko启动，luna可以正常访问，我执行mkdir他就报着错误了
附luna版本


![image](https://user-images.githubusercontent.com/21033020/59732099-77336380-927b-11e9-964a-9a0a9b9fa170.png)


我是完全按照https://jumpserver.readthedocs.io/zh/master/setup_by_centos7.html来安装的。

**Comment by glkappe** [comment]
@wojiushixiaobai  非常感谢

**Comment by LeeEirc** [comment]
@glkappe 你的过滤规则，可能存在问题，现已修复。

**Comment by glkappe** [comment]
@LeeEirc   非常感谢回复，我做了如下操作
docker stop jms_koko
docker rm jms_koko
docker rmi $(docker images -q)
(重新拉去了1.5的代码 )
 docker run --name jms_koko -d -p 2222:2222 -p 5000:5000 -e CORE_HOST=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e LOG_LEVEL=ERROR jumpserver/jms_koko:1.5.0



但是还是出现同样的问题，请问我需要怎么做操作呢，才可以应用咱们修复的这个代码

**Comment by wojiushixiaobai** [comment]
@glkappe 镜像我重新构建了，你删掉后，重新拉一下。

**Comment by glkappe** [comment]
@wojiushixiaobai  感谢，问下
docker run --name jms_koko -d -p 2222:2222 -p 5000:5000 -e CORE_HOST=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e LOG_LEVEL=ERROR jumpserver/jms_koko:1.5.0
有木有如上的命令可以执行？

**Comment by wojiushixiaobai** [comment]
@glkappe 
````
$ docker stop jms_koko
$ docker rm jms_koko
$ docker rmi jumpserver/jms_koko:1.5.0
$ Server_IP=`ip addr | grep inet | egrep -v '(127.0.0.1|inet6|docker)' | awk '{print $2}' | tr -d "addr:" | head -n 1 | cut -d / -f1`; fi
$ docker run --name jms_koko -d -p 2222:2222 -p 5000:5000 -e CORE_HOST=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e LOG_LEVEL=ERROR jumpserver/jms_koko:1.5.0

**Comment by glkappe** [comment]
@wojiushixiaobai  非常感谢 ~祝好
