### ISSUE TITLE
【建议】使用go mod换掉dep

### ISSUE THREAD

**Issue by jokimina** [jumpserver/koko#30]
go 1.12 是支持的
考虑使用go mod换掉dep么   结合 https://goproxy.io/zh/ 就不存在被墙的问题了

**Comment by jokimina** [comment]
以及docker images可以使用国内的阿里云免费镜像库  速度会快很多

**Comment by jokimina** [comment]
https://github.com/jokimina/koko/commit/381b18bdece19c47f6d883305923de9ff6037651

尝试性替换了下编译通过了 可以参考下  觉得可以的话 我改下README一起提交pr

**Comment by ibuler** [comment]
@LeeEirc 评估一下，
当时本来打算用 go mod的，发现不能replace某个库而用自己的库，所以放弃了

**Comment by ibuler** [comment]
接受，已merge

**Comment by jokimina** [comment]
好的 这个issue关闭了

https://github.com/jumpserver/koko/blob/master/pkg/service/urls.go

小小的吐槽下 这里命名的url后缀有的大写有的首字母大写 有的没url后缀...

**Comment by ibuler** [comment]
@LeeEirc

**Comment by ibuler** [comment]
@jokimina 非常感谢提的建议，项目伊始，还不是很完善，感谢帮助

**Comment by jokimina** [comment]
> @jokimina 非常感谢提的建议，项目伊始，还不是很完善，感谢帮助

您客气了  jumpserver是很棒的项目 帮到了我很多也学到了很多  共勉
