### ISSUE TITLE
大量屏幕打印时卡顿

### ISSUE THREAD

**Issue by xh-78** [jumpserver/koko#303]
版本信息如下:

Version:             2.0.0
Git Commit Hash:     2ca831dc4aa8673841d5eb8cc65c9a24f338d716
UTC Build Time :     2020-06-18 03:05:01AM
Go Version:          go version go1.14.2 darwin/amd64

当终端有大量打印信息或者屏幕频繁刷新时,卡顿会比较严重

**Comment by xh-78** [comment]
/pkg/proxy/recorder.go 去掉 ReplayRecorder Record 函数中的 file.Sync就可以了.  每次Sync是不是对磁盘要求有点高了吧

**Comment by LeeEirc** [comment]
@xh-78 感谢反馈，下个版本会去掉。
