### ISSUE TITLE
网域模式 一分钟自动断开

### ISSUE THREAD

**Issue by shuoliu1** [jumpserver/koko#305]
网域模式 proxy连接上服务器后1分钟无论是否持续输入都会断开
无法通过心跳检查,感觉像是和gateway的连接无法保持
1.5.9版本koko
![image](https://user-images.githubusercontent.com/16146661/86322810-359b0e00-bc6e-11ea-88d8-74acb9412e90.png)

**Comment by LeeEirc** [comment]
@shuoliu1 因为发送keepalive包失败，koko判定资产连接已经断开，会主动关闭。下个版本修改，keepalive包失败之后，将停止发送keepalive心跳包，不会主动关闭连接。

**Comment by LeeEirc** [comment]
@shuoliu1 使用v2.5版本，测试下是否还存在问题？
