### ISSUE TITLE
当保存账号密码后再登录，MFA验证就出现问题

### ISSUE THREAD

**Issue by zalmanzhao** [jumpserver/koko#35]
当保存账号密码后再登录，MFA验证出现的提示框就不对

**Comment by zalmanzhao** [comment]
![QQ截图20190714214517](https://user-images.githubusercontent.com/16017151/61184487-e5075b00-a680-11e9-8481-09971e9ba1a6.png)

**Comment by LeeEirc** [comment]
@zalmanzhao 由于xshell保存密码之后，遇到MFA认证时，使用了你保存的password，所以认证不成功，因此需要重新认证password和MFA。

**Comment by zalmanzhao** [comment]
但是老版本coco就不会

**Comment by ibuler** [comment]
确实存在问题

**Comment by LeeEirc** [comment]
@zalmanzhao 已经优化，下个版本修复。

**Comment by zalmanzhao** [comment]
nice

**Comment by LeeEirc** [comment]
1.5.2已修复。
