### ISSUE TITLE
SSH没有且无法添加密码输入错误次数过多临时Ban的功能

### ISSUE THREAD

**Issue by ShireCiel** [jumpserver/koko#352]
[简述你的问题]

##### 使用版本
[请提供你使用的 Koko 版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
重复的用相同的账户和不同的密码进行ssh连接，不会因为密码输入次数过多导致ban这个ip+账户的行为。可能会导致允许暴力破解密码。

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@ShireCiel 如果某账户一直登陆失败的话，账户会被锁定，无法登陆。

**Comment by ShireCiel** [comment]
> @ShireCiel 如果某账户一直登陆失败的话，账户会被锁定，无法登陆。

这个web界面倒是有功能。 但是ssh 自己试了很多次没有阻止ssh连接，也没有可以设置ssh错误次数过多ban的功能。

**Comment by LeeEirc** [comment]
@ShireCiel ssh可以连接，但是认证是无法通过的。

**Comment by ShireCiel** [comment]
的确 经过测试 ssh 可以连接，但是认证无法通过。
