### ISSUE TITLE
SSH命令解析的实现问题

### ISSUE THREAD

**Issue by owenliang** [jumpserver/koko#367]
我也在做类似koko的项目，目前有command解析的需求，因此参考了一下koko的实现。

根据koko代码来看，如果SSH服务端命令回显慢或者流量上行到sshd慢的话，inputState状态恢复为false，而此时SSH服务端尚未进行命令回显，那么就会错过本次命令的捕获。

如果我理解正确的话，似乎在这种proxy场景下没有完美的command捕获方案喽？

**Comment by LeeEirc** [comment]
命令解析就是来自服务端的返回值，非服务端agent的方式。
