### ISSUE TITLE
连接不释放的问题

### ISSUE THREAD

**Issue by eryajf** [jumpserver/koko#386]
##### 使用版本

```
./koko -V
Version:             1.5.9
Git Commit Hash:     26a3cefbedf5c84c9a8e29d22e73318e1af06eae
UTC Build Time :     2020-05-21 07:07:10AM
Go Version:          go version go1.14.2 darwin/amd64
```

##### 问题复现步骤

连接不会自动释放，累积到上限之后，就会报 `too many open files`了。

##### 具体表现

![](https://shop.io.mi-img.com/app/shop/img?id=shop_448bf431173c0df218b3b261d2591157.png)

**Comment by LeeEirc** [comment]
koko有报错信息吗？有多少会话？该服务器上只有 Koko吗？

**Comment by eryajf** [comment]
感谢回复！

现在我追踪到问题应该在命令存储到es这一环节的问题。服务器运行信息如下：

```
$ ps aux |grep koko
root     17864  4.9  2.0 866948 160892 ?       Sl   10:28  12:31 /opt/koko/koko
$ lsof -p 17864 | wc -l
3898
$ netstat -an | grep ESTAB | wc -l
4194
```

后来我们注意到，其中与es的建连是最多的：

```
netstat -an | grep ESTAB | grep 9200 | wc -l
3535
```

我们的确在堡垒机配置中设置了命令存储到es中，这个时候看到es当中有报错：

```
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Result window is too large, from + size must be less than or equal to: [10000] but was [41425]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting
```

这个错误是es的配置项限制所致，姑且可以判定为koko在往里边写入的时候，没有一个常规的时间戳字段，从而让所有的命令一股脑展示，这必然有问题。另一方面我很疑惑为什么koko与它有如此多的连接数，仿佛每执行一条命令，就会建立一个连接！

**Comment by LeeEirc** [comment]
@eryajf 命令记录是根据配置一次批量上传，如果上传失败，会持续不断重传，但数据可能会不断增大。如果上传成功了话，es的连接肯定会断开关闭。你可优先调整下es的配置，让命令记录批量上传成功。 Koko不会从es上获取命令数据。

**Comment by eryajf** [comment]
好的，我会尝试的。
不过还是想顺便提下命令写入到es的时间戳字段问题，看到在jumpserver里边已经有不少人提了这个[issue](https://github.com/jumpserver/jumpserver/issues?q=%E5%91%BD%E4%BB%A4%E5%AD%98%E5%82%A8)了，否则写入到es之后，越来越多，后期一定是不可维护的。

**Comment by ibuler** [comment]
@eryajf  ES 时间戳问题，怎么解决呢？ 或者应该怎么存储呢？这方面我们经验不是很充足，望举例

**Comment by eryajf** [comment]
感谢回复，希望这个问题能彻底解决，我这边整理了如下内容以作交流。

这里的痛点主要有两个方面，其一是索引时间戳的问题，其二是索引切割的问题，一个一个来说。

## 关于时间戳

基于es自身动态映射的机制，我这里用三个例子来说明问题

其一：完全没有时间戳字段

```
PUT /test/_doc/_bulk
{"index":{}}
{"message":"hello-01"}
{"index":{}}
{"message":"hello-02"}
{"index":{}}
{"message":"hello-03"}
```

其二：Unix时间戳，这个也是当前koko写入到es的格式，这种在es中默认被识别为`number`类型了，因此无法作为时间戳来解析

```
PUT /test1/_doc/_bulk
{"index":{}}
{"message":"hello-01","timestamp": 1593597117}
{"index":{}}
{"message":"hello-02","timestamp": 1593597118}
{"index":{}}
{"message":"hello-03","timestamp": 1593597119}
```

其三：es可识别的ISO8601时间格式

```
PUT /test2/_doc/_bulk
{"index":{}}
{"message":"hello-01","@timestamp":"2020-08-26T09:13:11.676+08:00"}
{"index":{}}
{"message":"hello-02","@timestamp":"2020-08-26T09:13:12.676+08:00"}
{"index":{}}
{"message":"hello-03","@timestamp":"2020-08-26T09:13:13.676+08:00"}
```

三个索引写入之后，在创建索引模式的时候就能发现，前两种方式都会提示不包含任何时间字段，第三种则会直接给到一个可供选择的时间字段。

通过截图来直观的查看效果，前两种方式结果一样，如下：

![image.png](https://shop.io.mi-img.com/app/shop/img?id=shop_09c95635bc86d11ff35bc3468eae1872.png)

而第三种展示的效果则如下：

![](https://shop.io.mi-img.com/app/shop/img?id=shop_09ad4378a0430ee7b795f4d697240cd8.png)

没有可供识别的时间戳的最大问题在于，经过半年的写入之后，可能有上亿条记录，也同样一下子展示，检索起来基本上不可用，当前koko基本上差不多已经符合了，只需要将timestamp合理的format一下，即可满足需求。

## 关于索引切割

这个切割问题不是一个很大的痛点了。通常情况下，我们习惯将索引按天来自动切割，比如logstash可以用如下方式进行表示：

```
output {
  elasticsearch {
    hosts => ["http://192.168.10.1:9200"]
    index => "test-%{+YYYY-MM-dd}"
  }
}
```


这样便于历史数据的清理，如果单个索引，可能需要定期重写一个新的索引，然后把老的索引删除了。

**Comment by ibuler** [comment]
也就是说，timestamp改成 ISO 格式的时间就行了，@timestamp 这个 key 是 timestamp 也没有关系吧

另外切割索引应该不行，搜索的时候，应就不方便了，可能跨好几个索引

**Comment by eryajf** [comment]
是的，没有关系，es会识别到这个时间字段。
跨索引的话，可以借助于索引别名来做，不过经过你这么说，似乎的确历史应该保留，这个问题可以保留！

**Comment by LeeEirc** [comment]
@eryajf v2.5上传到es时，已经添加时间字段。

**Comment by eryajf** [comment]
非常赞，我会在空闲的时间进行一下测试

**Comment by LeeEirc** [comment]
如有问题，再重新开启。
