### ISSUE TITLE
文件管理的错误提示和授权上传下载问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/koko#397]
[简述你的问题]
1：jumpserver在授权里只授权了上传下载，用户无法通过文件管理登录资产的sftp目录，建议在没授权连接的时候上传下载不可选
2：只授权了连接，用户在删除文件的时候没有提示没有权限，只是删除动作没有生效
2：通过测试，jumpserver如果取消了连接授权，web终端和文件管理都无法登录到资产，建议ssh连接和sftp连接分开授权
3：当没有授权连接权限的时候，用户在使用文件管理登录资产的sftp目录时，会提示文件夹不存在，建议提示管理员未授权xxx。
4：建议可以设置普通用户是否支持文件管理功能或者web终端功能，即没有文件管理选项或者web终端选项，

##### 使用版本
[请提供你使用的 Koko 版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44529247/90730233-5d1b6800-e2fa-11ea-987d-db51dc6cf9b3.png)

![image](https://user-images.githubusercontent.com/44529247/90730214-52f96980-e2fa-11ea-9130-4f68b2a50bc0.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
感谢反馈的一些问题，已经对web的文件管理的提示信息，进行了优化，尝试下v2.7的版本，如有问题，再反馈。
