### ISSUE TITLE
k8s 协议的数据库客户端未安装

### ISSUE THREAD

**Issue by typ431127** [jumpserver/koko#398]
[简述你的问题]
选择kubernetes应用显示:"k8s 协议的数据库客户端未安装"
##### 使用版本
版本:  v2.2.0-101

##### 问题复现步骤

![image](https://user-images.githubusercontent.com/20376675/91033656-4e082300-e636-11ea-8b85-082345028c4b.png)

**Comment by ibuler** [comment]
与之相同 https://github.com/jumpserver/koko/issues/398 ，在这个里面回复了
