### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by oldthreefeng** [jumpserver/koko#410]
ssh 连接失败

##### 使用版本
[请提供你使用的 Koko 版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
Koko Version 1.5.4, more see https://www.jumpserver.org
##### 问题复现步骤

使用官网搭建

##### 具体表现[截图可能会更好些,最好能截全]
```
TASK [ping] ********************************************************************
fatal: [junhsue-www]: UNREACHABLE! => {"changed": false, "msg": "Invalid/incorrect password: Permission denied, please try again.", "unreachable": true}
2020-09-09 09:20:24 任务结束
```
##### 其他
使用 `ssh  ip -p port` 是免秘登陆的.  但是使用`jumpserver` 就提示这个. 

[注:] 完成后请关闭 issue

**Comment by oldthreefeng** [comment]
很奇怪, 必须使用密码验证.  明明ssh命令可以使用秘钥的. 
在jumpserver里面就是不行. 使用密码就好了.

**Comment by bingws** [comment]
默认密码多少？我登录不上。

**Comment by oldthreefeng** [comment]
默认密码就是你使用 ssh -p port  host 
键盘输入的密码 @bingws
