### ISSUE TITLE
[ERRO] K8sCon command exit err: exit status 1

### ISSUE THREAD

**Issue by bingws** [jumpserver/koko#445]
运行koko，k8s连接不上，但是可以连上Linux资产
##### 使用版本
koko源码最新版

##### 问题复现步骤
1. 按照官方说明编译源码，运行./koko，连不上k8s，显示[ERRO] K8sCon command exit err: exit status 1

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/10806595/95323550-f0235800-08d0-11eb-82eb-54481d6b49e8.png)

##### 其他
使用dockers版本的没有这个问题，源码编译运行有这个问题。

**Comment by ibuler** [comment]
源码运行，需要把原生的 kuberctl 下载下来，放到一个目录   @LeeEirc @wojiushixiaobai 确定文档上有
