### ISSUE TITLE
ssh方式登录交换机 一分钟必断

### ISSUE THREAD

**Issue by positive-ly** [jumpserver/koko#459]
堡垒机直连交换机后1分钟无论是否持续输入都会断开

修改pkg/srvconn/connmanager.go文件 342行
`go KeepAlive(client, closed, 60) ` 
将60修改3600后则一个小时后断开
2.3.2版本koko 尝试单独替换 2.3.3版本koko后问题依旧存在

koko日志内报错keepalive心跳包发送失败

**Comment by LeeEirc** [comment]
@positive-ly 试一下v2.5的版本？

**Comment by positive-ly** [comment]
> @ positive-ly试一下v2.5的版本？

经测试问题已解决

**Comment by ryswork1993** [comment]
我是2.5.2，遇到了类似的问题，1分钟不操作之后就会无法再操作

**Comment by LeeEirc** [comment]
@ryswork1993 使用最新版本还存在问题吗？如有问题，直接qq 2970298425找到

**Comment by LeeEirc** [comment]
如有问题，再重新打开。
