### ISSUE TITLE
[Feature] koko主机名缩略

### ISSUE THREAD

**Issue by faith2god** [jumpserver/koko#471]
[简述你的问题]
备注字符超过一定量时，主机名被缩略

需求：
1. ID，主机名，IP任何情况下不缩略
2. 自定义显示列的个数，列的内容，以及列的长度

##### 使用版本
v2.4.2 

##### 问题复现步骤
1. 主机名足够长，如24字符
2. 备注足够长，如128字符

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16483557/97386041-f2943300-190d-11eb-9feb-7696c7d17502.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
@LeeEirc

**Comment by LeeEirc** [comment]
@faith2god 主机名没有做长度限制，主机名和备注都是依据终端窗口大小动态计算的宽度。终端窗口宽度毕竟有限，如果期望看到更全，可以全屏终端。
