### ISSUE TITLE
koko代码里 authClient.SetHeader("X-JMS-ORG", "ROOT") 改为 authClient.SetHeader("X-JMS-ORG", "DEFAULT")，排序就正常了，问下改为DEFAULT有没有其他影响？

### ISSUE THREAD

**Issue by lycclsltt** [jumpserver/koko#472]
koko代码里 authClient.SetHeader("X-JMS-ORG", "ROOT") 改为 authClient.SetHeader("X-JMS-ORG", "DEFAULT")，排序就正常了，问下改为DEFAULT有没有其他影响？

**Comment by LeeEirc** [comment]
这个选项与排序没有关系，默认KOKO组件的header `X-JMS-ORG`的值为`root`。排序问题，使用下最新的v2.4.x版本，应该已经解决。
