### ISSUE TITLE
[Bug] Telnet协议连接后，man、vi命令的显示出现滚动行

### ISSUE THREAD

**Issue by strangeryf** [jumpserver/koko#481]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.1

**浏览器版本**
无

**Bug 描述**
通过ssh命令，使用telnet协议连接某资产后，输入vi命令打开某个文件，之后会出现不断滚动的波浪号。输入man命令，则不断滚动，直到最后一页，无法往前翻页。

**Bug 重现步骤(有截图更好)**
1. 通过Win10的ssh命令连接到koko
2. 通过菜单选取某个支持telnet的资产
3. 连接后，运行vi，man等命令，出现显示问题

**Comment by ibuler** [comment]
截图一下，更直观

**Comment by strangeryf** [comment]
man的图不好截，vi截到其中一个场景
![vi](https://user-images.githubusercontent.com/10571918/99018297-b19a5080-2594-11eb-85dc-8371c7413115.png)

**Comment by LeeEirc** [comment]
@strangeryf 加我qq 2970298425，远程看下。

**Comment by strangeryf** [comment]
换putty试了一下，没有问题。看起来是win10自带的ssh.exe的问题。
