### ISSUE TITLE
[Bug] 通过jumpserver用ssh登录交换机1分钟无操作就无法再输入

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/koko#495]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.2

**浏览器版本**

**Bug 描述**
从2.3.0升级到2.5.2后出现连接交换机1分钟无操作之后，还是连接状态，但是无法再输入任何操作，而且这种情况下，会话还是在线的，无法手动终断

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
@ryswork1993 使用v2.6.1版本试试

**Comment by LeeEirc** [comment]
如存在问题，再打开。
