### ISSUE TITLE
提示语："请输入六位数字" 乱码

### ISSUE THREAD

**Issue by ccc-rrr** [jumpserver/koko#52]
通过 ssh -p2222 xxxx@ip ，连上后提示语："请输入六位数字" 为乱码。截图如下：

![image](https://user-images.githubusercontent.com/7959933/61518492-3c6c4900-aa3c-11e9-9cb5-e7544181941a.png)

暂未发现其他地方乱码。

**Comment by LeeEirc** [comment]
@ccc-rrr 已处理。
