### ISSUE TITLE
下载文件时候失败

### ISSUE THREAD

**Issue by neighbour-oldhuang** [jumpserver/koko#54]
2019/07/20 16:04:25 http: panic serving 172.8.8.130:50802: runtime error: invalid memory address or nil pointer dereference
goroutine 3376 [running]:
net/http.(*conn).serve.func1(0xc0008e0320)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0xe0e200, 0x18a81d0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/pkg/sftp.(*File).Close(0x0, 0xc00050a991, 0x7)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.0/client.go:770 +0x22
github.com/LeeEirc/elfinder.(*ElFinderConnector).dispatch(0xc0009ce120, 0x1120020, 0xc0002c6fc0, 0xc0006a9400)
        /go/pkg/mod/github.com/!lee!eirc/elfinder@v0.0.0-20190718023636-5679c8bdb7bf/elfinder.go:506 +0x43a
github.com/LeeEirc/elfinder.(*ElFinderConnector).ServeHTTP(0xc0009ce120, 0x1120020, 0xc0002c6fc0, 0xc0006a9400)
        /go/pkg/mod/github.com/!lee!eirc/elfinder@v0.0.0-20190718023636-5679c8bdb7bf/elfinder.go:56 +0x287
github.com/jumpserver/koko/pkg/httpd.sftpHostConnectorView(0x1120020, 0xc0002c6fc0, 0xc0006a9400)
        /opt/coco/pkg/httpd/elfhandler.go:96 +0x2fb
github.com/jumpserver/koko/pkg/httpd.AuthDecorator.func1(0x1120020, 0xc0002c6fc0, 0xc0008e2400)
        /opt/coco/pkg/httpd/elfhandler.go:47 +0x44e
net/http.HandlerFunc.ServeHTTP(0xc000032c70, 0x1120020, 0xc0002c6fc0, 0xc0008e2400)
        /usr/local/go/src/net/http/server.go:1995 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000244180, 0x1120020, 0xc0002c6fc0, 0xc0008e2200)
        /go/pkg/mod/github.com/gorilla/mux@v1.7.2/mux.go:212 +0xe3
net/http.serverHandler.ServeHTTP(0xc00026e750, 0x1120020, 0xc0002c6fc0, 0xc0008e2200)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0008e0320, 0x1123de0, 0xc000296c80)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4

**Comment by LeeEirc** [comment]
@neighbour-oldhuang 感谢反馈，已做优化。

**Comment by LeeEirc** [comment]
@neighbour-oldhuang 请问现在还有这个问题吗？
