### ISSUE TITLE
web文件管理无法识别软连接目录，xftp等软件无法在软连接目录里上传文件

### ISSUE THREAD

**Issue by lovese** [jumpserver/koko#59]
Linux系统，web文件管理无法识别软连接目录，显示为未知文件，xftp等软件无法在软连接目录里上传文件提示上传错误

**Comment by lovese** [comment]
docker 安装的 koko，页面上传或者xftp客户端上传都提示上传错误

**Comment by lovese** [comment]
经过多次测试，发现运维人员使用的是root账户登陆的服务器可以上传文件，开发人员使用的是普通账号登陆服务器的就无法上传文件，提示上传出错

**Comment by LeeEirc** [comment]
@lovese 首先要保证文件夹对所有用户都有权限。
