### ISSUE TITLE
1.5.2CPU过高

### ISSUE THREAD

**Issue by ccc-rrr** [jumpserver/koko#67]
版本：1.5.2
环境：docker
用户5人
问题：
![image](https://user-images.githubusercontent.com/7959933/62099903-3d19a080-b2c2-11e9-99b7-5bf1236a8015.png)

**Comment by LeeEirc** [comment]
@ccc-rrr 可以提供一下日志吗？检查是否是最新的docker镜像？

**Comment by ccc-rrr** [comment]
我在跟踪一下这个问题，重启后就恢复了。

**Comment by LeeEirc** [comment]
@ccc-rrr 好，可以加入koko的交流群908100817直接反馈。

**Comment by ccc-rrr** [comment]
好的。
跑一段时间就这样了：
![image](https://user-images.githubusercontent.com/7959933/63093968-9c053800-bf99-11e9-932f-1b3a6e9f9d41.png)

**Comment by LeeEirc** [comment]
@ccc-rrr 可以加qq群交流下。之前又做了一次更新，你升级一下版本？

**Comment by ccc-rrr** [comment]
已加群。用的是这个版本，还是会出现。
jumpserver/jms_koko        latest              7c6ce927b38d        11 days ago         39.5MB

**Comment by kk545141** [comment]
1.5.4的版本以及最新的版本依旧会存在这个问题。

**Comment by LeeEirc** [comment]
使用最新的1.5.6版本。
