### ISSUE TITLE
新旧版本KOKO/COCO 不兼容

### ISSUE THREAD

**Issue by shuhaoHuang** [jumpserver/koko#71]
# 新旧COCO\KOKO 共存，tcp 负载均衡流量无法到达

## 环境配置
- JMS 1.4.8-2
- DB Mysql 5.7
- Nginx 1.16
- COCO 1.4.8
- KOKO  1.5.0

## 存在问题
- 使用Nginx做tcp转发5000端口 负载均衡打到 旧的一个 localhost coco上和 两个docker 中的KOKO。当流量到达coco 可以正常访问。当流量到达koko时仅能打开sftp文件上传页面。无法打开ssh终端

**Comment by LeeEirc** [comment]
@shuhaoHuang 版本之间并不兼容，最好是统一版本使用。请使用最新的1.5.2

**Comment by junly917** [comment]
如果是从低版本升级过来的，如何将coco升级到koko, 我直接下载的koko包解压，修改了config.yml的文件，但是启动koko的时候提示，身份证信息未提供，有没有具体的升级操作指南
“2019-09-14 16:08:31 [ERRO] POST http://127.0.0.1:8080/api/terminal/v2/terminal-registrations/ failed, get code: 403, {"detail":"身份认证信息未提供。"}”

**Comment by LeeEirc** [comment]
@junly917 低版本升级，需要保证jumpserver也同步升级到同版本。另外配置文件里面的注册等信息需要一致，koko才能注册上。
