### ISSUE TITLE
koko进程经常自动停止

### ISSUE THREAD

**Issue by huangpeng0817** [jumpserver/koko#73]
koko1.5.2 ./koko & 后台运行后，经常运行一段时间后自动停掉，无报错日志，进程消失。需重新运行。之前使用coco 有直接后台运行命令，没有出现过这个问题。这个不清楚是啥问题，出现频繁，影响使用。已经又切回使用coco了。 还有koko啥时候可以自带 后台运行命令。

**Comment by LeeEirc** [comment]
@huangpeng0817 已经支持后台运行启动了。
