### ISSUE TITLE
koko命令行内：无法通过备注搜索主机

### ISSUE THREAD

**Issue by wanghkkk** [jumpserver/koko#75]
问题：
在主机中（apm01.pro.alibj.cn）增加备注pro_apm01，登陆koko时候备注一列是空的，但是针对于注意apm01.pro.alibj.cn是能看看到并且登陆的，并且已经r刷新成功。
如下图：

对主机授权：
![image](https://user-images.githubusercontent.com/21187778/63745737-88c96500-c8d5-11e9-805f-1a58a2bf76db.png)

通过koko，命令行登陆：只能看到主机，没有备注
![image](https://user-images.githubusercontent.com/21187778/63745671-5ddf1100-c8d5-11e9-8c49-4d38fc5635a8.png)

同样，无法通过备注搜索到主机：
![image](https://user-images.githubusercontent.com/21187778/63746495-8831ce00-c8d7-11e9-8f21-48331ab0ea23.png)

数据库内：是有备注的
![image](https://user-images.githubusercontent.com/21187778/63745839-c7f7b600-c8d5-11e9-9100-286fef773f20.png)

环境：
用户为LDAP，全部开启MAF
但是通过jumpserver内置用户测试也是这个问题。

版本：
jms：1.5.2
koko：1.5.2

错误日志：没有错误日志

**Comment by nikozhangwj** [comment]
![image](https://user-images.githubusercontent.com/36828806/63750710-90dad200-c8e0-11e9-8ef7-901d49bd65c1.png)
可以看下jumpserver/apps/perms/serializers 得AssetGrantedSerializer类是不是少写了个comment得字段

**Comment by wanghkkk** [comment]
> ![image](https://user-images.githubusercontent.com/36828806/63750710-90dad200-c8e0-11e9-8ef7-901d49bd65c1.png)
> 可以看下jumpserver/apps/perms/serializers 得AssetGrantedSerializer类是不是少写了个comment得字段

非常感谢，确实没有comment字段，添加上，然后重启即可。
具体的文件是：
jumpserver/apps/perms/serializers/user_permission.py

多个备注，可以用回车或者逗号分割。
