### ISSUE TITLE
更新到koko:1.5.0版本后，备注中的中文显示为乱码且显示不全。

### ISSUE THREAD

**Issue by jmucaicai** [jumpserver/koko#8]
外网港澳台-櫮..网:172.31.136.84)

**Comment by LeeEirc** [comment]
备注是自适应宽度，超过固定长度，则自动从中间截断，并不是显示不全。乱码可能是自动截断造成的。

**Comment by jmucaicai** [comment]
你好，这个有没有办法修复下。刚开始升到1.5.0的时候可以通过调整xshell的字体大小来让其显示完全。------------------ 原始邮件 ------------------
发件人: "Eric_Lee"<notifications@github.com>
发送时间: 2019年6月24日(星期一) 上午10:19
收件人: "jumpserver/koko"<koko@noreply.github.com>;
抄送: "jmucaicai"<292727249@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jumpserver/koko] 更新到koko:1.5.0版本后，备注中的中文显示为乱码且显示不全。 (#8)



备注是自适应宽度，超过固定长度，则自动从中间截断，并不是显示不全。乱码可能是自动截断造成的。
 
&mdash;

**Comment by LeeEirc** [comment]
@jmucaicai 已经放开备注的长度限制，修复乱码问题。

**Comment by jmucaicai** [comment]
好的，非常感谢。跪谢。


 
---原始邮件---
发件人: "Eric_Lee"<notifications@github.com>
发送时间: 2019年6月24日(星期一) 下午3:12
收件人: "jumpserver/koko"<koko@noreply.github.com>;
抄送: "jmucaicai"<292727249@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [jumpserver/koko] 更新到koko:1.5.0版本后，备注中的中文显示为乱码且显示不全。 (#8)



@jmucaicai 已经放开备注的长度限制，修复乱码问题。

**Comment by wojiushixiaobai** [comment]
@jmucaicai 已经更新，请更新镜像。
shell````
$ docker stop jms_koko
$ docker rm jms_koko
$ docker rmi jumpserver/jms_koko:1.5.0
$ Server_IP=`ip addr | grep inet | egrep -v '(127.0.0.1|inet6|docker)' | awk '{print $2}' | tr -d "addr:" | head -n 1 | cut -d / -f1`
$ docker run --name jms_koko -d -p 2222:2222 -p 5000:5000 -e CORE_HOST=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_koko:1.5.0

**Comment by jmucaicai** [comment]
您好，目前已经更新好最新版本的koko版本，使用中，感觉棒极了，需要跪谢作者。
目前使用中还有点小问题，就是使用koko1.5.0版本的时候，xshell界面会偶然间卡死（在使用vim命令和top -c），只能重新退出xshell界面，重新登录。还有就是xshell的显示界面，还是希望能够像coco1.4.9版本的展示界面一样。不适用自适应，主机名和备注能够完全展示。由使用者来控制xshell界面的展示。纯属个人愚见。

**Comment by LeeEirc** [comment]
@jmucaicai 最新1.5.2版本已经取消了主机名和备注的显示限制。目前代码已经做了改善，应该解决了卡死问题。可以使用最新版本体验。

**Comment by nilnaijgnid** [comment]
> 您好，目前已经更新好最新版本的koko版本，使用中，感觉棒极了，需要跪谢作者。
> 目前使用中还有点小问题，就是使用koko1.5.0版本的时候，xshell界面会偶然间卡死（在使用vim命令和top -c），只能重新退出xshell界面，重新登录。还有就是xshell的显示界面，还是希望能够像coco1.4.9版本的展示界面一样。不适用自适应，主机名和备注能够完全展示。由使用者来控制xshell界面的展示。纯属个人愚见。

你好，问下你在升级到koko过程中有没有遇到ssh认证的问题，比如要删除客户端known_hosts中记录才能连koko的问题？

**Comment by LeeEirc** [comment]
@nilnaijgnid  ssh登录时，客户端需要记录ssh服务器的公钥。你从coco更换成koko之后，公钥发生变化了，所以你在登录时，需要删除原来的公钥信息。这是正常的。

**Comment by nilnaijgnid** [comment]
@LeeEirc 清理known_hosts是可以解决的，但是因为用户比较多，而且大多数都是开发，如果每个人都要清理一遍的话，对用户不太友好，请问有从服务端解决的办法吗？另外以后每升级一次koko都要清理known_hosts吗？

**Comment by LeeEirc** [comment]
@nilnaijgnid  备份使用原来的access_key，默认路径是在 `data/keys/.access_key`。

**Comment by nilnaijgnid** [comment]
@LeeEirc 我尝试了一下，把coco的.access_key文件拷贝到koko的目录下，再重启koko，还是不行，MD5对比了两个access_key，没有差异。

**Comment by LeeEirc** [comment]
@nilnaijgnid koko的私钥都是由jumpserver分发的，应该都是一样的才对。 koko与coco的`data/keys/host_key`也是一样的吗？

**Comment by nilnaijgnid** [comment]
@LeeEirc host_rsa_key文件也是我从coco下面拷贝过来的，md5也是一样的

**Comment by LeeEirc** [comment]
@nilnaijgnid  文件名称不一样，koko用的是host_key. coco是用的host_rsa_key.

**Comment by nilnaijgnid** [comment]
@LeeEirc 我🈶尝试了以下2种方案
1. 把host_rsa_key重命名为host_key，重启服务，不行
2. 删除host_rsa_key，没有自动下发，重启服务，这样也不行
另外我发现无论host_rsa_key文件是否存在，客户端的known_hosts中记录的内容都是一样的，是不是和这个文件没关系呢

**Comment by LeeEirc** [comment]
@nilnaijgnid 这个就是koko作为ssh server的私钥。按理说，都是一样的。那么下发给客户端的公钥，都是一样的。

**Comment by nilnaijgnid** [comment]
@LeeEirc 还是没解决，我再看下吧，谢谢啦
