### ISSUE TITLE
koko 1.5.2报错

### ISSUE THREAD

**Issue by kentwanwan** [jumpserver/koko#81]
2019-09-10 19:56:24 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
koko一直在报这个错，怎么解决？配置上没有什么不对的地方。

**Comment by LeeEirc** [comment]
@kentwanwan 检查一下luna是否是最新的版本。如果网络有类似nginx的代理，需要配置支持websocket. nginx的配置类似于这样。
`proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

**Comment by kentwanwan** [comment]
@LeeEirc 我的nginx配置是配置了这些的。
 location /socket.io/ {
        proxy_pass       http://localhost:5000/socket.io/;  
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

**Comment by kentwanwan** [comment]
哎！无奈中带着悲伤。重启nginx解决。
